# Generated by Django 4.0.4 on 2024-10-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_qr_code_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='qr_code_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
